In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv("Barcelona.csv")

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15406 entries, 0 to 15405
Data columns (total 19 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              15406 non-null  int64
 1   name                            15406 non-null  object
 2   host_id                         15293 non-null  float64
 3   host_profile_id                 15212 non-null  float64
 4   host_name                       15206 non-null  object
 5   neighbourhood_group             15406 non-null  object
 6   neighbourhood                   15406 non-null  object
 7   latitude                        15406 non-null  float64
 8   longitude                       15406 non-null  float64
 9   room_type                       15406 non-null  object
 10  price                           13465 non-null  float64
 11  minimum_nights                  15405 non-null  float64
 12  number_of_reviews               15406 non-null  int64
 13  last_review                     11822 non-null  object
 14  reviews_per_month               11822 non-null  float64
 15  calculated_host_listings_count  15293 non-null  float64
 16  availability_365                15406 non-null  int64
 17  number_of_reviews_ltm           15406 non-null  int64
 18  license                         12250 non-null  object
dtypes: float64(8), int64(4), object(7)
memory usage: 2.2+ MB

In [ ]:
#Inciso A 
nombres_distintos = df['host_name'].unique()[:5] #definimos la variable donde se guardan los nombres, y se especifica que sean distintos y solo 5
filtroA = df[df['host_name'].isin(nombres_distintos)]
filtroA

,id,name,host_id,host_profile_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
0,18674,Huge flat for 8 people close to Sagrada Familia,71615.0,1.462508e+18,Maria Y Mireia Barcelona4Seasons,Eixample,la Sagrada Família,41.405560,2.172620,Entire home/apt,409.0,1.0,59,2026-05-28,0.37,20.0,123,9,Spain - National registration number<br />ESFC...
1,23197,CCIB Forum· Large Balcony · 5 min walk to CCIB,90417.0,1.462509e+18,Marnie,Sant Martí,el Besòs i el Maresme,41.412432,2.219750,Entire home/apt,388.0,2.0,99,2026-06-07,0.53,1.0,239,11,Spain - National registration number<br />ESFC...
2,34981,VIDRE HOME PLAZA REAL on LAS RAMBLAS,73163.0,1.462508e+18,Andres,Ciutat Vella,el Barri Gòtic,41.379780,2.176230,Entire home/apt,397.0,1.0,304,2026-05-26,1.59,2.0,329,37,Spain - National registration number<br />ESFC...
3,36763,In front of the beach,158596.0,1.462511e+18,Ester,Ciutat Vella,la Barceloneta,41.380370,2.192720,Private room,43.0,31.0,108,2023-12-13,0.60,1.0,38,0,NaN
4,40983,Architect's Loft near Gaudí & Passeig de Gràcia,177617.0,1.462512e+18,Joaquin,Eixample,la Dreta de l'Eixample,41.396310,2.168320,Entire home/apt,226.0,1.0,450,2026-06-19,2.46,5.0,289,56,Barcelona - Regional registration number<br />...
126,569610,Pl España / Sants Station / Perfect Remote Work,2700806.0,1.462605e+18,Andres,Sants-Montjuïc,Sants,41.375180,2.140260,Entire home/apt,235.0,5.0,58,2026-06-14,0.34,1.0,43,5,Barcelona - Regional registration number<br />...
210,775644,Stylish Apt w/Terrace | City Center,177617.0,1.462512e+18,Joaquin,Eixample,la Nova Esquerra de l'Eixample,41.381027,2.152186,Entire home/apt,179.0,1.0,476,2026-06-14,2.93,5.0,296,64,Barcelona - Regional registration number<br />...
282,934979,Sagrada Familia charming,5044674.0,1.462672e+18,Ester,Eixample,la Sagrada Família,41.400583,2.175099,Entire home/apt,326.0,2.0,701,2026-06-20,4.32,1.0,142,70,Spain - National registration number<br />ESFC...
373,1119598,Flat with views to Sagrada Famila,71615.0,1.462508e+18,Maria Y Mireia Barcelona4Seasons,Eixample,la Sagrada Família,41.404570,2.172150,Entire home/apt,405.0,3.0,269,2026-06-22,1.88,20.0,136,23,Spain - National registration number<br />ESFC...
669,2288221,Elegant apartment in the heart of the city,71615.0,1.462508e+18,Maria Y Mireia Barcelona4Seasons,Eixample,Sant Antoni,41.377210,2.164290,Entire home/apt,375.0,1.0,293,2026-04-22,1.97,20.0,128,21,Spain - National registration number<br />ESFC...
695,2394424,Chic studio in a perfect location in Barcelona,71615.0,1.462508e+18,Maria Y Mireia Barcelona4Seasons,Eixample,l'Antiga Esquerra de l'Eixample,41.387230,2.156310,Entire home/apt,169.0,1.0,185,2026-06-10,1.26,20.0,161,31,Spain - National registration number<br />ESFC...
802,3000464,Barcelona center apartment (2 Adults + 2 Child...,71615.0,1.462508e+18,Maria Y Mireia Barcelona4Seasons,Eixample,l'Antiga Esquerra de l'Eixample,41.385320,2.162310,Entire home/apt,187.0,1.0,268,2026-06-05,1.82,20.0,149,42,Barcelona - Regional registration number<br />...
837,3167271,Sagrada Familia Views: Premier Tourist Apartment,1029387.0,1.462536e+18,Andres,Eixample,la Sagrada Família,41.407430,2.174230,Entire home/apt,260.0,2.0,423,2026-06-13,2.89,1.0,89,27,Barcelona - Regional registration number<br />...
909,3481808,Apat. close to Sagrada Familia,71615.0,1.462508e+18,Maria Y Mireia Barcelona4Seasons,Eixample,la Sagrada Família,41.404520,2.178600,Entire home/apt,NaN,1.0,58,2026-06-04,0.42,20.0,113,13,Spain - National registration number<br />ESFC...
914,3495408,Apartment for groups near Sagrada Familia,71615.0,1.462508e+18,Maria Y Mireia Barcelona4Seasons,Eixample,la Sagrada Família,41.402300,2.171810,Entire home/apt,247.0,1.0,20,2026-06-08,0.21,20.0,153,4,Barcelona - Regional registration number<br />...
951,3744593,Apt with cozy terrace,71615.0,1.462508e+18,Maria Y Mireia Barcelona4Seasons,Eixample,l'Antiga Esquerra de l'Eixample,41.385000,2.157950,Entire home/apt,237.0,2.0,142,2026-06-08,1.06,20.0,144,20,Spain - National registration number<br />ESFC...
1100,4970715,Recently renovated and quiet ap.,71615.0,1.462508e+18,Maria Y Mireia Barcelona4Seasons,Eixample,la Nova Esquerra de l'Eixample,41.384320,2.146650,Entire home/apt,189.0,1.0,133,2026-06-03,1.09,20.0,120,18,Spain - National registration number<br />ESFC...
1132,5197640,Apartment in the center of the city,71615.0,1.462508e+18,Maria Y Mireia Barcelona4Seasons,Eixample,l'Antiga Esquerra de l'Eixample,41.388480,2.156070,Entire home/apt,142.0,2.0,201,2026-06-10,1.51,20.0,130,39,Spain - National registration number<br />ESFC...
1336,7003642,Modern apartment with terrace,71615.0,1.462508e+18,Maria Y Mireia Barcelona4Seasons,Gràcia,el Camp d'en Grassot i Gràcia Nova,41.407820,2.165530,Entire home/apt,201.0,1.0,117,2026-05-31,0.96,20.0,126,13,Spain - National registration number<br />ESFC...
4197,35832249,Luxury Apartment Park Güell,269531884.0,1.469424e+18,Ester,Horta-Guinardó,el Carmel,41.418060,2.151240,Entire home/apt,263.0,2.0,170,2026-05-23,2.01,1.0,346,33,Barcelona - Regional registration number<br />...
4701,40745175,Apartamento moderno cerca del Camp Nou,71615.0,1.462508e+18,Maria Y Mireia Barcelona4Seasons,Les Corts,les Corts,41.382670,2.129860,Entire home/apt,67.0,32.0,0,NaN,NaN,20.0,241,0,Spain - National registration number<br />ESFC...
5659,49984706,"With Private Bathroom & Terrace, AC+600MbWifi",177617.0,1.462512e+18,Joaquin,Sarrià-Sant Gervasi,les Tres Torres,41.394410,2.132740,Private room,49.0,31.0,22,2025-07-21,0.37,5.0,72,2,Spain - National registration number<br />ESHF...
5660,49984968,"With Private Terrace, 600Mb Wifi and AC",177617.0,1.462512e+18,Joaquin,Sarrià-Sant Gervasi,les Tres Torres,41.392610,2.132410,Private room,40.0,31.0,22,2026-01-25,0.36,5.0,65,2,Spain - National registration number<br />ESHF...
5672,50083428,"With Shared Terrace, AC and 600Mb Wifi",177617.0,1.462512e+18,Joaquin,Sarrià-Sant Gervasi,les Tres Torres,41.392690,2.133080,Private room,40.0,31.0,21,2026-05-26,0.35,5.0,62,2,Spain - National registration number<br />ESHF...
6708,598210258384760217,Modern apartment close to the Camp Nou Stadium,71615.0,1.462508e+18,Maria Y Mireia Barcelona4Seasons,Les Corts,la Maternitat i Sant Ramon,41.384050,2.127580,Entire home/apt,249.0,2.0,115,2026-06-01,2.31,20.0,135,26,Spain - National registration number<br />ESFC...
7018,660751128618376242,"Cozy and comfy apt, excellent location",18135683.0,1.463037e+18,Ester,Gràcia,el Camp d'en Grassot i Gràcia Nova,41.408890,2.165970,Entire home/apt,83.0,31.0,1,2022-08-24,0.02,2.0,327,0,NaN
7256,709852017663835707,"Apartment in prime location, perfect for families",71615.0,1.462508e+18,Maria Y Mireia Barcelona4Seasons,Eixample,l'Antiga Esquerra de l'Eixample,41.386073,2.158339,Entire home/apt,229.0,2.0,37,2026-06-05,0.81,20.0,140,6,Spain - National registration number<br />ESFC...
7836,833787902115935031,Apartamento muy cerca Ramblas,71615.0,1.462508e+18,Maria Y Mireia Barcelona4Seasons,Ciutat Vella,el Raval,41.378170,2.171760,Entire home/apt,67.0,32.0,0,NaN,NaN,20.0,287,0,Spain - National registration number<br />ESFC...
8204,887395817973157589,Penthouse with Private Terrace,71615.0,1.462508e+18,Maria Y Mireia Barcelona4Seasons,Horta-Guinardó,el Guinardó,41.415596,2.178491,Entire home/apt,179.0,2.0,98,2026-05-23,2.72,20.0,116,26,Spain - National registration number<br />ESFC...
8504,925319046707863327,Apartamento al lado de la playa,71615.0,1.462508e+18,Maria Y Mireia Barcelona4Seasons,Ciutat Vella,la Barceloneta,41.381588,2.186889,Entire home/apt,56.0,32.0,4,2025-11-01,0.15,20.0,332,2,Spain - National registration number<br />ESFC...
8542,932569596868861320,3 suite apartment near Ramblas,73163.0,1.462508e+18,Andres,Ciutat Vella,el Barri Gòtic,41.380860,2.174800,Entire home/apt,224.0,31.0,0,NaN,NaN,2.0,170,0,NaN
8600,938985742501827154,Estudi lluminós i ben comunicat,18135683.0,1.463037e+18,Ester,Horta-Guinardó,el Baix Guinardó,41.410220,2.166090,Entire home/apt,96.0,31.0,0,NaN,NaN,2.0,87,0,NaN
9054,1013882465790024892,Room with Balcony in Central Barcelona,176514024.0,1.468710e+18,Andres,Eixample,l'Antiga Esquerra de l'Eixample,41.387369,2.155789,Private room,123.0,1.0,19,2026-06-09,4.83,2.0,170,19,NaN
9055,1013883984435259564,Private Interior Room in Central BCN,176514024.0,1.468710e+18,Andres,Eixample,l'Antiga Esquerra de l'Eixample,41.387078,2.154044,Private room,81.0,1.0,26,2026-06-08,6.90,2.0,166,26,NaN
10345,1175955069246165077,Comfortable apartment next to Sagrada Familia,71615.0,1.462508e+18,Maria Y Mireia Barcelona4Seasons,Eixample,la Sagrada Família,41.405540,2.171720,Entire home/apt,224.0,2.0,42,2026-02-20,1.72,20.0,156,12,Spain - National registration number<br />ESFC...
10709,1229525461082470897,"La mejoresvistasde Barcelona, terraza 90 m pri...",49635010.0,1.462714e+18,Joaquin,Ciutat Vella,la Barceloneta,41.377860,2.190530,Entire home/apt,413.0,31.0,0,NaN,NaN,1.0,49,0,Spain - National registration number<br />ESFC...
11018,1284590816663751175,Cómodo apartamento cerca metro,71615.0,1.462508e+18,Maria Y Mireia Barcelona4Seasons,Sants-Montjuïc,Sants - Badal,41.372092,2.131134,Entire home/apt,56.0,32.0,0,NaN,NaN,20.0,177,0,Spain - National registration number<br />ESFC...
11564,1353550843022453659,"Single room, private bathroom",677542508.0,1.470695e+18,Ester,Eixample,el Fort Pienc,41.397006,2.178069,Private room,37.0,31.0,1,2025-07-18,0.09,5.0,297,1,Spain - National registration number<br />ESHF...
11569,1354179659690182026,"Habitación, aire acondicionado",677542508.0,1.470695e+18,Ester,Eixample,la Dreta de l'Eixample,41.396912,2.177099,Private room,36.0,31.0,8,2026-05-31,0.58,5.0,299,6,Spain - National registration number<br />ESHF...
11576,1355608539769151419,"Room, private fridge + A/C",677542508.0,1.470695e+18,Ester,Eixample,el Fort Pienc,41.396962,2.177635,Private room,30.0,31.0,4,2025-09-17,0.29,5.0,317,2,Spain - National registration number<br />ESHF...
13382,1539038626939475945,Acogedor Studio Sants a 15' Bcn Centro y Fira Bcn,725607185.0,1.539039e+18,Ester,Sants-Montjuïc,Sants,41.374530,2.133030,Entire home/apt,292.0,3.0,2,2026-02-07,0.30,1.0,85,2,Barcelona - Regional registration number<br />...
13683,1581374715746154776,"Habitación, baño privado, aire acondicionado",677542508.0,1.470695e+18,Ester,Eixample,el Fort Pienc,41.395985,2.177433,Private room,45.0,31.0,0,NaN,NaN,5.0,213,0,Barcelona - Regional registration number<br />...
13684,1581388718734887536,"Tranquila habitación, aire acondicionado",677542508.0,1.470695e+18,Ester,Eixample,el Fort Pienc,41.395985,2.177433,Private room,28.0,31.0,2,2026-05-21,0.69,5.0,158,2,Barcelona - Regional registration number<br />...
14479,1665062821024992480,"Apartment, close to an entrance of Park Güell",71615.0,1.462508e+18,Maria Y Mireia Barcelona4Seasons,Gràcia,el Coll,41.419310,2.149990,Entire home/apt,126.0,32.0,0,NaN,NaN,20.0,206,0,Spain - National registration number<br />ESFC...

In [8]:
filtroA.to_csv("Inciso A.csv")

## LA HOJA DE DATOS DE MI PAÍS NO TIENE VARIABLE DE "HOST_SINCE" , "HOST_RESPONSE_TIME" , "BEDS"

In [ ]:
# Inciso D
multiplos = df.iloc[200::200]
multiplos

,id,name,host_id,host_profile_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
200,753322,Big beautiful apartment in Gracia 4 rooms,3962572.0,1.462644e+18,Magda,Gràcia,la Vila de Gràcia,41.399420,2.156180,Entire home/apt,369.0,4.0,251,2026-06-08,1.55,2.0,297,14,Barcelona - Regional registration number<br />...
400,1198074,Two bedroom apartment,6544866.0,1.462709e+18,Juan,Eixample,la Dreta de l'Eixample,41.391960,2.173770,Entire home/apt,240.0,1.0,125,2026-06-17,1.00,12.0,257,28,Barcelona - Regional registration number<br />...
600,1920941,Luxurious & Loving Apartment,9935841.0,1.462827e+18,Sheila,Les Corts,les Corts,41.384210,2.138560,Entire home/apt,310.0,4.0,99,2026-06-07,0.65,1.0,340,15,Barcelona - Regional registration number<br />...
800,2996993,Large two bedroom apartment,6544866.0,1.462709e+18,Juan,Eixample,la Dreta de l'Eixample,41.391960,2.173730,Entire home/apt,370.0,1.0,73,2026-06-02,0.50,12.0,233,13,Barcelona - Regional registration number<br />...
1000,4114081,Barcelona | Apt near Sagrada Familia for 6,299462.0,1.462511e+18,Stay Unique,Eixample,la Dreta de l'Eixample,41.401920,2.170761,Entire home/apt,444.0,1.0,339,2026-06-09,2.38,140.0,340,26,Spain - National registration number<br />ESFC...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14600,1677477937703824479,Eixample town - 365 barcelona rentals,14544418.0,1.462941e+18,Iñigo Barcelona,Eixample,la Nova Esquerra de l'Eixample,41.383643,2.154023,Entire home/apt,175.0,1.0,4,2026-06-08,2.40,5.0,329,4,Spain - National registration number<br />ESFC...
14800,1689843502743720327,Charming room near the beach and the center,504431152.0,1.470268e+18,Victor,Sants-Montjuïc,el Poble Sec,41.374842,2.164296,Private room,103.0,2.0,2,2026-06-11,2.00,2.0,28,2,Spain - National registration number<br />ESFC...
15000,1698509847890521632,Cómoda habitación en la zona de montjuic con aire,31538271.0,1.462655e+18,Hola Barcelona,Sants-Montjuïc,la Font de la Guatlla,41.370322,2.146028,Private room,160.0,1.0,0,NaN,NaN,22.0,357,0,Spain - National registration number<br />ESFC...
15200,1708774165763933382,Cozy 3BR Apartment: Great Location in L'Eixample,1447144.0,1.462518e+18,Acomodis Apartments,Eixample,la Nova Esquerra de l'Eixample,41.379667,2.147980,Entire home/apt,451.0,1.0,0,NaN,NaN,448.0,198,0,Barcelona - Regional registration number<br />...
15400,1714436799055988275,Tranquila habitación con balcón y a/a.,159231006.0,1.463005e+18,Natalia,Eixample,el Fort Pienc,41.399540,2.179510,Private room,28.0,31.0,0,NaN,NaN,5.0,143,0,Barcelona - Regional registration number<br />...

In [11]:
multiplos.to_csv("Inciso D.csv")

In [12]:
# Inciso E
tipos_cuartos = df[df['room_type'].isin(['Entire home/apt','Private room'])]
tipos_cuartos

,id,name,host_id,host_profile_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
0,18674,Huge flat for 8 people close to Sagrada Familia,71615.0,1.462508e+18,Maria Y Mireia Barcelona4Seasons,Eixample,la Sagrada Família,41.405560,2.172620,Entire home/apt,409.0,1.0,59,2026-05-28,0.37,20.0,123,9,Spain - National registration number<br />ESFC...
1,23197,CCIB Forum· Large Balcony · 5 min walk to CCIB,90417.0,1.462509e+18,Marnie,Sant Martí,el Besòs i el Maresme,41.412432,2.219750,Entire home/apt,388.0,2.0,99,2026-06-07,0.53,1.0,239,11,Spain - National registration number<br />ESFC...
2,34981,VIDRE HOME PLAZA REAL on LAS RAMBLAS,73163.0,1.462508e+18,Andres,Ciutat Vella,el Barri Gòtic,41.379780,2.176230,Entire home/apt,397.0,1.0,304,2026-05-26,1.59,2.0,329,37,Spain - National registration number<br />ESFC...
3,36763,In front of the beach,158596.0,1.462511e+18,Ester,Ciutat Vella,la Barceloneta,41.380370,2.192720,Private room,43.0,31.0,108,2023-12-13,0.60,1.0,38,0,NaN
4,40983,Architect's Loft near Gaudí & Passeig de Gràcia,177617.0,1.462512e+18,Joaquin,Eixample,la Dreta de l'Eixample,41.396310,2.168320,Entire home/apt,226.0,1.0,450,2026-06-19,2.46,5.0,289,56,Barcelona - Regional registration number<br />...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15401,1714453367636295798,Sagrada Familia View — Diagonal White Loft T5A...,114338664.0,1.468178e+18,Balcons De Barcelona,Eixample,la Sagrada Família,41.401970,2.179467,Entire home/apt,94.0,32.0,0,NaN,NaN,27.0,359,0,Barcelona - Regional registration number<br />...
15402,1714507108958061169,Sagrada Familia - Diagonal Industrial Loft T5A...,114338664.0,1.468178e+18,Balcons De Barcelona,Eixample,la Sagrada Família,41.401970,2.179467,Entire home/apt,94.0,32.0,0,NaN,NaN,27.0,359,0,Barcelona - Regional registration number<br />...
15403,1714524223290226460,Cozy 2-Bedroom Apartment in Poble Sec for 4 pe...,1447144.0,1.462518e+18,Acomodis Apartments,Sants-Montjuïc,el Poble Sec,41.374546,2.163292,Entire home/apt,183.0,1.0,0,NaN,NaN,448.0,121,0,Barcelona - Regional registration number<br />...
15404,1714528494413566181,Poble Sec - Lovely 2BR Apartment with Terrace,1447144.0,1.462518e+18,Acomodis Apartments,Sants-Montjuïc,el Poble Sec,41.374546,2.163292,Entire home/apt,263.0,1.0,0,NaN,NaN,448.0,114,0,Barcelona - Regional registration number<br />...
15405,1714531569719409706,Great 2-Bedroom Apartment • Poble Sec • 4 people,1447144.0,1.462518e+18,Acomodis Apartments,Sants-Montjuïc,el Poble Sec,41.374546,2.163292,Entire home/apt,263.0,1.0,0,NaN,NaN,448.0,132,0,Barcelona - Regional registration number<br />...

In [13]:
tipos_cuartos.to_csv("Inciso E.csv")

In [14]:
columna_impares = df.iloc[:,1::2]
columna_impares

,name,host_profile_id,neighbourhood_group,latitude,room_type,minimum_nights,last_review,calculated_host_listings_count,number_of_reviews_ltm
0,Huge flat for 8 people close to Sagrada Familia,1.462508e+18,Eixample,41.405560,Entire home/apt,1.0,2026-05-28,20.0,9
1,CCIB Forum· Large Balcony · 5 min walk to CCIB,1.462509e+18,Sant Martí,41.412432,Entire home/apt,2.0,2026-06-07,1.0,11
2,VIDRE HOME PLAZA REAL on LAS RAMBLAS,1.462508e+18,Ciutat Vella,41.379780,Entire home/apt,1.0,2026-05-26,2.0,37
3,In front of the beach,1.462511e+18,Ciutat Vella,41.380370,Private room,31.0,2023-12-13,1.0,0
4,Architect's Loft near Gaudí & Passeig de Gràcia,1.462512e+18,Eixample,41.396310,Entire home/apt,1.0,2026-06-19,5.0,56
...,...,...,...,...,...,...,...,...,...
15401,Sagrada Familia View — Diagonal White Loft T5A...,1.468178e+18,Eixample,41.401970,Entire home/apt,32.0,NaN,27.0,0
15402,Sagrada Familia - Diagonal Industrial Loft T5A...,1.468178e+18,Eixample,41.401970,Entire home/apt,32.0,NaN,27.0,0
15403,Cozy 2-Bedroom Apartment in Poble Sec for 4 pe...,1.462518e+18,Sants-Montjuïc,41.374546,Entire home/apt,1.0,NaN,448.0,0
15404,Poble Sec - Lovely 2BR Apartment with Terrace,1.462518e+18,Sants-Montjuïc,41.374546,Entire home/apt,1.0,NaN,448.0,0
15405,Great 2-Bedroom Apartment • Poble Sec • 4 people,1.462518e+18,Sants-Montjuïc,41.374546,Entire home/apt,1.0,NaN,448.0,0

In [15]:
columna_impares.to_csv("Inciso G.csv")